
import "./globals.css";
import { Inter } from "next/font/google";

import Link from "next/link";





const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;


}) {


  // const urlPrimeraOpcion = "http://localhost:3000";
  // const urlSegundaOpcion = "https://nest-online-build.onrender.com";


  return (<>


    <html lang="en">
      <body className={inter.className}>

        <div className=" flex justify-end items-center gap-5 relative bg-blue-800	pr-5 w-full h-16  ">
          <h1 className="text-white font-bold">
            Edición menu
          </h1>
          <Link className="text-white font-bold" href="/perfil">
            perfil
          </Link>
          <Link className="text-white font-bold" href="/contactos">
            contactos
          </Link>
          <Link className="text-white font-bold" href="/productos">
            productos
          </Link>
          <Link className="text-white font-bold" href="/crud">
            crud
          </Link>
        </div>

        {children}
      </body>
    </html>
  </>
  );
}
